export const FETCH_MOVIES = 'FETCH_MOVIES';
export const CLEAR_FETCH_MOVIES = 'CLEAR_FETCH_MOVIES';
export const FETCH_ONE_MOVIE = 'FETCH_ONE_MOVIE';
export const CLEAR_ONE_FETCH_MOVIE = 'CLEAR_ONE_FETCH_MOVIE';